export {Cart} from './Cart/Cart'
export {Home} from './Home/Home'
export {Login} from './Login/Login'
export {NotFound} from './NotFound/NotFound'
export {Pizza} from './Pizza/Pizza'
export {Profile} from './Profile/Profile'
export {Register} from './Register/Register'